# Generated by Django 3.0.8 on 2021-02-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'contacts'},
        ),
        migrations.AddField(
            model_name='contact',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='contacts',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='contact',
            name='jabber',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='contact',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contact',
            name='other_contacts',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='skype',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
